version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  task-service:
    build: ./task-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
